nuke-ops/Nostra-13

code/datums/components/field_of_vision.dm
code/game/machinery/doors/airlock.dm
config/game_options.txt

Enables fov and fixes airlock emmissive lights

---

code/datums/martial/cqc.dm
code/datums/martial/krav_maga.dm
code/datums/martial/plasma_fist.dm
code/datums/martial/psychotic_brawl.dm
code/datums/martial/rising_bass.dm
code/datums/martial/sleeping_carp.dm
code/datums/martial/wrestling.dm
code/modules/mob/living/simple_animal/simplemob_vore_values.dm
code/modules/vore/eating/belly_dat_vr.dm
code/modules/vore/eating/bellymodes.dm

Made mob xenomorphs , giant spiders , grillas and goliaths vorable and digestable
healing ability of vore nerfed
digestation damage of vore slighly buffed in term of burn damage
now all bellies should have a default 15% chances of being escaped by pressing the resist button

some buffs , nerfs and other changes to vore

---

modular_nostration/code/game/objects/items/stunbaton.dm

Adding parry flag to stunsword

---

code/__HELPERS/_cit_helpers.dm

No no no we don't touch each other through clothes by sorcery

Fixing lewd checks

---

code/game/objects/structures/crates_lockers/closets/secure/security.dm

:cl:
tweak: tweaked a few things
/:cl:

General map changes vol. 3.1

---

code/modules/mob/say.dm

fixing say indicators

---

appveyor.yml

uh, appveyor 'fix'

---

code/controllers/configuration/entries/general.dm
config/config.txt
interface/interface.dm
interface/skin.dmf

:cl:
del: Removed forum link
add: Added discord link
/:cl:

Replaces forum button with a discord button

---

modular_nostration/code/_onclick/hud/screen_objects.dm
tgstation.dme

Adds actions to health doll.
You can... click it if you can't click yourself directly, also works for examines!
Example, you're in a locker, and need to heal without leaving it.
:cl:
code: Adds a Click command for the healthdoll.
/:cl:

[Sandstorm port] Healthdoll Changes

---

code/modules/vore/eating/belly_dat_vr.dm
code/modules/vore/eating/bellymodes.dm

vore is too op
:cl:
balance: nerfed vore
/:cl:

Vore minor nerf

---

code/controllers/configuration/entries/general.dm
code/modules/admin/admin_verbs.dm
code/modules/client/darkmode.dm
modular_nostration/code/modules/admin/verbs/fix_air.dm
tgstation.dme

Air fixing is good, just as bugfixing.
Revert mistakes and fix the discord, how can we get peeps like that!
:cl:
add: Added a new admin command, "Fix air", choose a range and get breathable air!
fix: Fixed discord button being a forum button that does nothing.
/:cl:

[Sandstorm port] Adds tgstation's fix air for admins

---

_maps/map_files/OmegaStation/OmegaStation2deck_nostration.dmm
_maps/map_files/OmegaStation/OmegaStation_nostration.dmm

maybe
yes
:cl:
fix: fixed a few things
/:cl:

Minor map fixes

---

_maps/map_files/OmegaStation/OmegaStation2deck_nostration.dmm
_maps/map_files/OmegaStation/OmegaStation_nostration.dmm
modular_nostration/code/game/area/Space_Station_13_areas.dm

Yes
Yar
:cl:
fix: fixed a few things
/:cl:

Moar map fixes/area fixes

---

_maps/map_files/OmegaStation/OmegaStation2deck_nostration.dmm
_maps/map_files/OmegaStation/OmegaStation_nostration.dmm
modular_nostration/code/game/area/Space_Station_13_areas.dm

Fixes yes yes
Yes fix always good yes yes
:cl:
fix: fixed a few things yes
/:cl:

fix yes yes

---

_maps/map_files/OmegaStation/OmegaStation2deck_nostration.dmm
_maps/map_files/OmegaStation/OmegaStation_nostration.dmm
modular_nostration/code/game/area/Space_Station_13_areas.dm

aka more fixes
:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

Lets hope thats a last one for now.

---

_maps/map_files/OmegaStation/OmegaStation2deck_nostration.dmm
_maps/map_files/OmegaStation/OmegaStation_nostration.dmm

yes
:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

Omega Fixes

---

_maps/map_files/OmegaStation/OmegaStation2deck_nostration.dmm
_maps/map_files/OmegaStation/OmegaStation_nostration.dmm

Reworked HoS office - It's not too big and uselessly empty anymore
Reworked Warden office - It's not too small anymore
Reworked Armory
Added Perma prison

Omega security rework

---

_maps/map_files/OmegaStation/OmegaStation2deck_nostration.dmm
_maps/map_files/OmegaStation/OmegaStation_nostration.dmm

Fixed rooms in dorms - now they should bolt correctly
Added escape chance from perma - only for the smart ones
Fixed pipe and cable problems
Fixed shutter problems
Fixed  area problems
Fixed SM Driver being destroyed when shit hits the fan - Driver intended to yeet sm when everything else failed, burned to a crisp and failed.

Major Omega Fixes

---

_maps/map_files/MetaStation/MetaStation.dmm
_maps/map_files/MetaStation/MetaStation_nostration.dmm
_maps/map_files/OmegaStation/OmegaStation.dmm
_maps/map_files/OmegaStation/OmegaStation2deck_nostration.dmm
_maps/map_files/OmegaStation/OmegaStation_nostration.dmm

Fixed areas on Omega
Moved Engineering Protolathe to a new place.

Map tweaks

---

_maps/map_files/OmegaStation/OmegaStation2deck_nostration.dmm
_maps/map_files/OmegaStation/OmegaStation_nostration.dmm

Added Labor Shuttle on Omega
Minor Omega Fixes

Labor Shuttle

---

modular_nostration/code/game/objects/items/storage/backpack.dm

Some preloaded bags for mappers
:cl:
add: Added science duffel bag with medical tools
add: Added science duffel bag with circuit tools
add: Added science duffel bag with nanite tools
add: Added science duffel bag with roboticist tools
/:cl:

Preloaded duffel bags

---

_maps/map_files/OmegaStation/OmegaStation2deck_nostra.dmm
_maps/map_files/OmegaStation/OmegaStation_nostra.dmm

maybe fix
maybe
fix
:cl:
fix: maybe fixed elevator
/:cl:

maybe fixed elevator

---

_maps/map_files/OmegaStation/OmegaStation2deck_nostra.dmm
_maps/map_files/OmegaStation/OmegaStation_nostra.dmm

don wanna
:cl:
tweak: revisited few rooms in engineering and RnD
/:cl:

Even more thingies

---

modular_sand/code/modules/mob/living/silicon/robot/robot_modules.dm

when you're engineering borg, with tools and stuff to fix station and usually, you're not having a lot of interactions with humans, and you have hecking dildo, cos yes, who the fuck designed it. (I mean, I know who made it but I don't understand, why would you do that, dirty ligger)
how borgs with dildos could be good for the game
:cl:
tweak: removed dildos from all borgs but service
/:cl:

I'm not even gonna comment that.

---

_maps/map_files/OmegaStation/OmegaStation_nostra.dmm

Added "gas the slimes"™ chamber
now you can gas slimes and tators
no
:cl:
add: Added "gas the slimes" chamber on Omega Station.
tweak: Changed some color tiles to more smooth ones.
fix: Fixed area in Medbay.
/:cl:

Omega Xenobio Expansion

---

_maps/map_files/OmegaStation/OmegaStation2deck_nostra.dmm
_maps/map_files/OmegaStation/OmegaStation_nostra.dmm

Cargo Elevator is working again.
Also, both lower and upper location marker now has proper names for their levels.
:cl:
fix: added location marker for upper level, along with swapping the ID for lower level location marker
/:cl:

Cargo Elevator fix

---

_maps/map_files/OmegaStation/OmegaStation2deck_nostra.dmm
_maps/map_files/OmegaStation/OmegaStation_nostra.dmm
_maps/shuttles/cargo_elevator.dmm

Cargo tweaks
yes
no
:cl:
tweak: Repositioned elevator in cargo. 
/:cl:

Cargo tweaks

---

_maps/map_files/OmegaStation/OmegaStation_nostra.dmm
_maps/shuttles/cargo_elevator.dmm

yes
yes
no
:cl:
fix: No more 1500+ kpa in cargo
/:cl:

more fixes

---

modular_sand/code/game/objects/items/circuitboards/machine_circuitboards.dm
modular_sand/code/modules/mining/machine_bluespaceminer.dm

^
Lazy miners goes brrr
:cl:
balance: bluespace miner costs now 10 bp crystals instead of 5
balance: bluespace miner is gathering half of materials that it was mining before
/:cl:

Who doesn't like nerfs? Bluespace miner edition.

---

_maps/map_files/OmegaStation/OmegaStation2deck_nostra.dmm
_maps/map_files/OmegaStation/OmegaStation_nostra.dmm
_maps/shuttles/cargo_elevator.dmm

see title
yes
no
:cl:
fix: Realigned cargo conv. belt on second deck
tweak: """"balanced"""" some maintenace drops
/:cl:

Realigned cargo conveyor belt

---

_maps/RandomRuins/SpaceRuins/oldstation.dmm

Ported reworked charlie station because for some reason we still had old smelly one.
yes
yes
:cl:
del: Removed old charlie station.
add: Added new charlie station.
/:cl:

Make Charlie Station great again

---

_maps/RandomRuins/SpaceRuins/oldstation.dmm

^
:cl:
fix: fixed holes on charliestation
/:cl:

fixed holes on charliestation

---

code/datums/components/crafting/recipes/recipes_misc.dm
modular_sand/code/datums/components/crafting/recipes/recipes_misc.dm

How lazy you can be sand ligger.
-Making omni protolathe is way too easy, and allows you to craft easily new armory anywhere.
-Blackmarket is too easy too obtain and allows you to build antagonist stuff.
:cl:
balance: changed recipe of omni protolathe, now it need all department lathe circuits to build it
balance: added emag to requirements to build blackmarket
/:cl:

Nerf omnilathe and blackmarket recipe

---

code/datums/components/crafting/recipes/recipes_misc.dm
code/modules/cargo/blackmarket/blackmarket_uplink.dm
modular_sand/code/datums/components/crafting/recipes/recipes_misc.dm

:cl:
tweak: tweaked a omnilathe recipe
balance: blackmarket recipe doesn't require emag anymore, instead you emag to access warehouse tab
/:cl:

Second rebalance for blackmarket and omnilathe

---

modular_sand/code/modules/cargo/blackmarket/blackmarket_items/gadgets.dm

_Generally current warehouse is not good for the game_, we'll have to finally rework it.. 
@AnonChangechong  @SVX-0 **do something.**
:cl:
balance: replaced emag with emag charges in warehouse
/:cl:

Just another warehouse nerf

---

code/game/objects/items/crayons.dm
code/game/turfs/simulated/floor.dm

Some random tweaks
:cl:
tweak: allowed spray to use a bit darker colors
fix: fixed RCD not able to build door at firelocks
/:cl:

Random tweaks

---

_maps/map_files/PubbyStation/PubbyStation_nostra.dmm

Paramedic office on Pubby
Why there is no paramedic office on Pubby ?
Paramedic good.
Death bad.
:cl:
add: Adds two paramedic offices on Pubby Station.
/:cl:

Paramedic office on Pubby

---

_maps/map_files/OmegaStation/OmegaStation2deck_nostra.dmm
_maps/map_files/OmegaStation/OmegaStation_nostra.dmm

Omega security checkpoint fix
Omega security checkpoint fix
Omega security checkpoint fix
:cl:
fix: Fixes lack of cable under the airlock to security checkpoint on Omega.
tweak: Moved few tables in security checkpoint on Omega to make it '''better'''.
/:cl:

Omega security checkpoint fix

---

modular_sand/code/game/objects/items/circuitboards/machine_circuitboards.dm
modular_sand/code/modules/research/techweb/bluespace_nodes.dm

:cl:
balance: Bluespace miner now costs 5 refined bluespace crystals
balance: Bluespace miner research now requires alien tech research node
/:cl:

bp miner rebalance, I hope people will like it

---

_maps/map_files/OmegaStation/OmegaStation2deck_nostra.dmm
_maps/map_files/OmegaStation/OmegaStation_nostra.dmm

:cl:
fix: Fixed lack of pipe and cable under the airlock to escape lounge on OmegaStation.
fix: Fixed maint areas on OmegaStation.
tweak: Moved HoS office to Warden office and Warden office to HoS office on OmegaStation.
/:cl:

cable, pipe and maint area fix

---

_maps/map_files/BoxStation/BoxStation_nostra.dmm
_maps/map_files/Deltastation/DeltaStation2_nostra.dmm
_maps/map_files/MetaStation/MetaStation_nostra.dmm
_maps/map_files/OmegaStation/OmegaStation_nostra.dmm
_maps/map_files/PubbyStation/PubbyStation_nostra.dmm

:cl:
fix: The "Monke table" is now reachable on OmegaStation.
tweak: Doubled and improved Paramedic offices on maps.
tweak: Added Paramedic office on DeltaStation.
/:cl:

Map updates

---

_maps/RandomRuins/SpaceRuins/oldstation.dmm
_maps/map_files/BoxStation/BoxStation_nostra.dmm
_maps/map_files/MetaStation/MetaStation_nostra.dmm

:cl:
fix: Fixed nanitelab access on few maps.
tweak: No more rushing xeno satelite on charlie station to change into xenomorph.
/:cl:

Nanitelab access

---

_maps/RandomRuins/SpaceRuins/madxenobiologist.dmm
code/game/objects/structures/ghost_role_spawners.dm
modular_nostra/code/game/objects/structures/ghost_role_spawners.dm
tgstation.dme

Also I fixed up the Mad Xenobiologist description too be up-to-date with what is currently planned, and also so you didn't have to do it SadChangeling.
Also added the necessary parts to make a Chem Dispenser so you can actually make the Mutation Toxins. *With the battery missing so you have to make a slime battery*
Updating the ghost role to be proper.
Just an update.
Nope.
:cl:
add: Chem Dispenser board *Without battery*
tweak: Mad Xenobiologist Ghost Role description.
/:cl:

Fixed Mad Xenobiologist.

---

_maps/RandomRuins/SpaceRuins/madxenobiologist.dmm
_maps/map_files/KiloStation/KiloStation_nostra.dmm

:cl:
fix: Fixed doubled spare on KiloStation.
fix: Fixed walls in mad xenobio ship.
fix: Fixed creatures pens in mad xenobio ship.
/:cl:

csbvdnjkoi

---

_maps/map_files/BoxStation/BoxStation_nostra.dmm
_maps/map_files/DIYstation/DIYstation.dmm
_maps/map_files/Deltastation/DeltaStation2_nostra.dmm
_maps/map_files/LambdaStation/lambda_nostra.dmm
_maps/map_files/MetaStation/MetaStation_nostra.dmm
_maps/map_files/OmegaStation/OmegaStation_nostra.dmm
_maps/map_files/PubbyStation/PubbyStation_nostra.dmm
_maps/map_files/SmolStation/SmolStation_nostra.dmm
_maps/map_files/Snaxi/Snaxi_nostra.dmm

:cl:
add: Added prisoner job spawners.
/:cl:

prisoner job spawners

---

_maps/map_files/KiloStation/KiloStation_nostra.dmm

added jerry to cargo, added a small cargo outpost on the outer asteroid as seen on TG
:cl:
add: added jerry to cargo, added a small cargo outpost on the outer asteroid as seen on TG
/:cl:

kilostation fuckery and shit ya know what i mean

---

_maps/map_files/DiscStation/DiscStation.dmm
code/datums/shuttles.dm
code/modules/mob/dead/new_player/sprite_accessories/body_markings.dm

just a few fixes for disc and a personal thing i wanted changed for an eternity
Fixes shit on DiscStation
Its good if you want a new semi working station lol
deez
:cl:
add: cryogenic to dorm
add: added a few things here and there in bar, including a jukebox. i tried.
add: added Action Figures all over DiscStation.
add: added more vendors to every department.
add: put a few things into cargo to sell, very useful.
fix: HOPEFULLY fixed the shuttle issue on DiscStation
fix: added Pipes to Disc Atmos that were missing.
tweak: changed access on the maintenance doors going from engie hall and departures hall to brig maint, also changed departures bar access to bartender only
tweak: Moth fluff no longer hidden when wearing hardsuits. (i hope)
balance: removed the deagle mags from vault, obvious …

fixes n shit

---

_maps/map_files/DiscStation/DiscStation.dmm
_maps/shuttles/arrival_disc.dmm

just a few fixes.
:cl:
add: added a emergency toolbox to each arrival shuttle pod
add: added missing lathes to departments
add: added a axes to atmos and bridge
fix: added a few missing wires and wired a few wires to the main grid
del: removed some windows in the windowed space maintenance so the doors can close
/:cl:

Disc station1.2

---

_maps/map_files/DiscStation/DiscStation.dmm
_maps/shuttles/emergency_disc.dmm

more fixes
more fixes yaaaaaaay
:cl:
add: Added cams to xenobio
add: added a few wires missing
add: added a few buttons to areas so people dont get locked in
add: added forgotten cameras in xenobio and moved a table
add: added a few pipes and fixes the toxins chamber
fix: fixed mineral piles across the station
/:cl:

DiscStation1.3

---

_maps/map_files/DiscStation/DiscStation.dmm

few changes n shit
fixes and stuff for discstation
map
:cl:
add: Added a locker with old stuff.
del: Removed the door leading into space in maints, completely useless and made that room its own tiny wall mistery.
tweak: changed the atmos room in arrivals to be atmos only, since you can pretty much sabotage atmos from there.
fix: fixed the buttons that didnt close shutters, yay!
/:cl:

DiscStation1.4

---

_maps/map_files/DiscStation/DiscStation.dmm

fixes
:cl:
del: Removed tazer, very sad
del: removed tiny fans in some pod bays
fix: fixed solar smes being setup weird
fix: fixed shutters
/:cl:

Disc station1.5

---

_maps/map_files/DiscStation/DiscStation.dmm

changes to disc
:cl:
add: Changed the garden and exanded the brig locker room
/:cl:

DiscStation-1.7

---

_maps/map_files/SmolStation/SmolStation_nostra.dmm

Third part of Smol Rework - Medbay
:cl:
tweak: Reworked medbay on SmolStation.
/:cl:

Smol Station 3: gods help me

---

_maps/map_files/SmolStation/SmolStation_nostra.dmm

:cl:
fix: Connected disposal system in SmolStation medbay.
fix: Deleted useless pipes leading to nothing on SmolStation.
fix: Added more lights in SmolStation medbay.
/:cl:

Smol medbay fixes

---

dependencies.sh
tools/bootstrap/node
tools/bootstrap/node.bat
tools/bootstrap/node_.ps1
tools/bootstrap/python37._pth
tools/bootstrap/python_.ps1

I wonder if it will work
Should fix problems with some tools like mapmerge
:cl:
experiment: took tg's bootstrap
/:cl:

steal tg's bootstrap
